config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  resources :tweets, only: :index
  resources :schedules, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :time, uniqueness: true, presence: true

  class << self
    def available?
      time_now = Time.now
      hour = time_now.hour
      minute = time_now.min
      schedule_time = Time.new(2000,1,1, hour, minute)

      where(time: schedule_time).present?
    end
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :external_id, :content, :username, :tweeted_at, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:edit, :update, :destroy]

  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new(time: Time.now)
  end

  def edit
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to schedules_path
    else
      render :new
    end
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to schedules_path
    else
      render :edit
    end
  end

  def destroy
    @schedule.destroy
    redirect_to schedules_path
  end

  private

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    { time: parse_time }
  end

  def permit_params
    params.require(:schedule).permit('time(4i)', 'time(5i)')
  end

  def parse_time
    Time.new(2000,1,1,permit_params['time(4i)'], permit_params['time(5i)'],0,"+01:00")
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.order(tweeted_at: :desc).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def link_to_tweet(tweet)
    link_to 'Show tweet', "https://twitter.com/statuses/#{tweet.external_id}"
  end

  def link_to_user(tweet)
    link_to tweet.username, "https://twitter.com/#{tweet.username}"
  end

  def tweeted_date(tweet)
    "Tweeted: #{tweet.tweeted_at.strftime('%Y-%m-%d %I:%M %p')}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterFeeder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.slim
= form_for @schedule do |f|
  = f.time_select :time, { ampm: true }
  = f.submit 'Save'

app/views/schedules/edit.slim
h1 Edit Schedule
= render 'form'

app/views/schedules/index.slim
h1 Schedules

p= link_to 'Add Schedule', new_schedule_path

table
  thead
    tr
      td Time
      td
      td
  tbody
    - @schedules.each do |schedule|
      tr
        td= schedule.time.strftime("%I:%M %p")
        td= link_to 'Edit', edit_schedule_path(schedule)
        td= link_to 'Delete', schedule_path(schedule), method: :delete

app/views/schedules/new.slim
h1 New Schedule
= render 'form'

app/views/tweets/index.slim
h1 Tweets

p= link_to "Schedules", schedules_path

table
  thead
    tr
      td
      td
      td
      td
      td
  tbody
    - @tweets.each do |tweet|
      tr
        td= image_tag(tweet.avatar)
        td= link_to_user(tweet)
        td= tweet.content
        td= tweeted_date(tweet)
        td= link_to_tweet(tweet)

= paginate @tweets